demo:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200
      index:
        number-of-replicas: 0
        number-of-shards: 3
      account:
        username: elastic
        password: czy1024
